/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static ViewModel.ViewProducts.TableData;
import static ViewModel.ViewProducts.setData;
import javax.swing.JFrame;

/**
 *
 * @author Merna
 */
public class Dessert extends javax.swing.JFrame implements Node {
private Node n;
View table;

    /**
     * Creates new form Dessert
     */
    public Dessert(JFrame parent) {
        initComponents();
        this.setTitle("Desserts");
        this.setSize(520,350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moltencake = new javax.swing.JButton();
        waffle = new javax.swing.JButton();
        view = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        moltencake.setText("Molten Cake");
        moltencake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moltencakeActionPerformed(evt);
            }
        });
        getContentPane().add(moltencake);
        moltencake.setBounds(30, 50, 97, 56);

        waffle.setText("Waffle");
        waffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waffleActionPerformed(evt);
            }
        });
        getContentPane().add(waffle);
        waffle.setBounds(30, 140, 96, 50);

        view.setIcon(new javax.swing.ImageIcon("C:\\Users\\Merna\\Downloads\\icons8-eye-24.png")); // NOI18N
        view.setText("View order");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view);
        view.setBounds(30, 260, 130, 50);

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Merna\\Downloads\\icons8-go-back-24.png")); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(210, 260, 120, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/55b72b9b-6b9f-4e8c-a5f9-88a27d5d0275.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 510, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void waffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waffleActionPerformed
        // TODO add your handling code here:
        DetailsWindow w= new DetailsWindow(2);
          w.setVisible(true);
        w.setParentNode(this);
        this.setVisible(false);
    }//GEN-LAST:event_waffleActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
          this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void moltencakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moltencakeActionPerformed
        // TODO add your handling code here:
          DetailsWindow m= new DetailsWindow(1);
          m.setVisible(true);
        m.setParentNode(this);
        this.setVisible(false);
    }//GEN-LAST:event_moltencakeActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:

                if(table==null)
    {String[] header={"ID","Name","Price","Quantity"};
        table=new View(header);
        table.setTitle("View Orders");
    }
        String mydata[][] =TableData(table);
        setData(mydata,table.getJTable(),table.columns);
        table.setParentNode(this);
        this.setVisible(false);
        table.setVisible(true);

 
        
    }//GEN-LAST:event_viewActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton moltencake;
    private javax.swing.JButton view;
    private javax.swing.JButton waffle;
    // End of variables declaration//GEN-END:variables

     @Override
    public Node getParentNode() {
        return n;
    }

    @Override
    public void setParentNode(Node node) {
        this.n=node;
    }
}
